spring:
  activiti:
    database-schema-update: true
    jpa-enabled: false
  datasource:
    url: jdbc:h2:mem:activiti;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456

  h2:
    console:
      path: /h2-console
      enabled: true

